# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout (with submodules)
      uses: actions/checkout@v4
      with:
          submodules: recursive
          fetch-depth: 0

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-

    - name: Setup Node.js (LTS)
      uses: actions/setup-node@v4
      with:
          node-version: 20
          cache: npm
          cache-dependency-path: ui/package-lock.json

    - name: Install UI deps
      working-directory: ui
      run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Lint (clippy)
      run: cargo clippy -- -D warnings

    - name: Format check
      run: cargo fmt -- --check
